version: '3.6'
services:
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mongodb
      - elasticsearch
      - java-app
    links:
      - influxdb
      - mongodb
      - elasticsearch
      - java-app
    ports:
      - '127.0.0.1:8125:8125/udp'

  influxdb:
    image: influxdb:1.8
    env_file: configuration.env
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - grafana
      - mongodb
      - elasticsearch
      - influxdb

  java-app:
    image: tig-java-app:latest
    container_name: java-app
    ports:
      - "8082:8082"
      - "8778:8778"
    depends_on:
      - mongodb
      - elasticsearch
      - influxdb

volumes:
  grafana_data: {}
  influxdb_data: {}
  mongodb_data: {}
  esdata: {}
